version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "spellcheck/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "object_detection/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "logo-ann/benchmark/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "data4good_logo_detection/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "nutrition-table-extraction/models_test/graphNN/TIES-2.0/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "logo-ann/generation/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
