version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: "pip"
    directory: "spellcheck/requirements.txt" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "object_detection/requirements.txt" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "logo-ann/benchmark/requirements.txt" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "logo-ann/generation/requirements.txt" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "data4good_logo_detection/requirements.txt" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "nutrition-table-extraction/models_test/graphNN/TIES-2.0/requirements.txt" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "logo-ann/generation/requirements_ml.txt" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "pip"
    directory: "logo-ann/generation/requirements_streamlit.txt" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 300
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      include: "scope"
